//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SED.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumnos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alumnos()
        {
            this.Asignatura_Alumno = new HashSet<Asignatura_Alumno>();
            this.Secion = new HashSet<Secion>();
        }
    
        public int id_alumno { get; set; }
        public string matricula { get; set; }
        public string nombre { get; set; }
        public int fk_id_carrera { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public int fk_id_tipoEvaluador { get; set; }
        public string correo_universitario { get; set; }
    
        public virtual Carrera Carrera { get; set; }
        public virtual Tipo_Evaluador Tipo_Evaluador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asignatura_Alumno> Asignatura_Alumno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Secion> Secion { get; set; }
    }
}
