//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SED.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Evaluacion
    {
        public int id_detalle_evaluacion { get; set; }
        public int fk_id_evaluacion { get; set; }
        public int fk_id_pregunta { get; set; }
        public int fk_id_respuesta { get; set; }
    
        public virtual Evaluacion Evaluacion { get; set; }
        public virtual Pregunta Pregunta { get; set; }
    }
}
