//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SED.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Directores_Escuelas
    {
        public int id_director { get; set; }
        public string codigo_empleado { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public string correo_universitario { get; set; }
        public string nombre { get; set; }
        public int fk_id_escuela { get; set; }
    
        public virtual Escuela Escuela { get; set; }
    }
}
