//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SED.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evaluacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Evaluacion()
        {
            this.Detalle_Evaluacion = new HashSet<Detalle_Evaluacion>();
            this.Docente_Evaluacion = new HashSet<Docente_Evaluacion>();
        }
    
        public int id_evaluacion { get; set; }
        public int fk_id_tipo_evaluador { get; set; }
        public int fk_id_periodo { get; set; }
        public string estado { get; set; }
        public int fk_id_tipo_cuestionario { get; set; }
        public System.DateTime fecha_registro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Evaluacion> Detalle_Evaluacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Docente_Evaluacion> Docente_Evaluacion { get; set; }
        public virtual Periodo Periodo { get; set; }
        public virtual Tipo_Evaluador Tipo_Evaluador { get; set; }
    }
}
