//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SED.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pregunta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pregunta()
        {
            this.Detalle_Evaluacion = new HashSet<Detalle_Evaluacion>();
            this.Detalle_Pregunta = new HashSet<Detalle_Pregunta>();
            this.Preguntas_Cuestionario = new HashSet<Preguntas_Cuestionario>();
        }
    
        public int id_pregunta { get; set; }
        public int fk_id_categoria_pregunta { get; set; }
        public int fk_id_tipo_pregunta { get; set; }
        public string nombre_pregunta { get; set; }
        public string pregunta1 { get; set; }
        public System.DateTime fecha_registro { get; set; }
    
        public virtual Categoria_Pregunta Categoria_Pregunta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Evaluacion> Detalle_Evaluacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Pregunta> Detalle_Pregunta { get; set; }
        public virtual Tipo_Pregunta Tipo_Pregunta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Preguntas_Cuestionario> Preguntas_Cuestionario { get; set; }
    }
}
